# Generated by Django 4.2.7 on 2025-04-25 07:20

import complaints.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=100, verbose_name='Project Name')),
                ('short_info', models.CharField(help_text='Brief description of the project', max_length=200, verbose_name='Short Info')),
                ('program', models.TextField(help_text='Detailed program description', max_length=1000, verbose_name='Program')),
                ('started_date', models.DateField(help_text='Date when the project started', verbose_name='Started Date')),
                ('deadline_date', models.DateField(help_text='Expected completion date of the project', verbose_name='Deadline Date')),
                ('identification_no', models.CharField(help_text='Unique identification number for the project', max_length=50, verbose_name='Identification No')),
                ('selected_contractor', models.CharField(help_text='Name of the contractor working on the project', max_length=100, verbose_name='Selected Contractor')),
                ('related_document', models.FileField(blank=True, help_text='Any relevant document for the project', null=True, upload_to=complaints.models.get_upload_path, verbose_name='Related Document')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes about the project', max_length=400, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
                'unique_together': {('identification_no',)},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Content of the comment', max_length=1000, verbose_name='Comment Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this comment', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(help_text='Project this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='complaints.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
